### ISSUE TITLE
 npm install: npm ERR! TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by arasharchor** [yosuke-furukawa/smile_shot#2]
Hi

today I was trying your codes in computer vision. when I am trying run "npm install", I get the following error.

┌─majid:~/smile_shot 
└────>> npm install
npm http GET http://registry.npmjs.org/opencv
npm http GET http://registry.npmjs.org/smile-face-detector
npm http GET http://registry.npmjs.org/gcloud
npm http GET http://registry.npmjs.org/eater
npm http GET http://registry.npmjs.org/must-call
npm http GET http://registry.npmjs.org/power-assert
npm http 304 http://registry.npmjs.org/opencv
npm http 304 http://registry.npmjs.org/smile-face-detector
npm http 304 http://registry.npmjs.org/gcloud
npm http 304 http://registry.npmjs.org/must-call
npm http 304 http://registry.npmjs.org/eater
npm http 304 http://registry.npmjs.org/power-assert
npm http GET http://registry.npmjs.org/slack/client
npm http 404 http://registry.npmjs.org/slack/client
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-92-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/majid/smile_shot
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/majid/smile_shot/npm-debug.log
npm ERR! not ok code 0

**Comment by yosuke-furukawa** [comment]
You should update node. my smile_shot does not support node v0.10. I support node v6,v5,v4.

**Comment by arasharchor** [comment]
@yosuke-furukawa thanks for your help :+1:
